apiVersion: v1
kind: Pod
metadata:
  name: pod-with-resources
  namespace: learning
spec:
  containers:
    - name:  my-container
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "120Mi"
          cpu: "260m"
      readinessProbe:
        httpGet:
          path: /
          port: 80