apiVersion: v1
kind: Pod
metadata:
  name: pod-with-resources
  namespace: learning
spec:
  containers:
    - name:  my-container
      image: nginx/nginx-unprivileged
      env:      # Setting environment variables from configmap (app-cm)
      - name: APP_ENV      
        valueFrom:
         configMapKeyRef:
          name: my-app-config
          key: APP_ENV
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "120Mi"
          cpu: "260m"
      readinessProbe:
        httpGet:
          path: /
          port: 80
