apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  namespace: learning
spec:
  volumes:
  - name: pv-volume-storage
    persistentVolumeClaim:
      claimName: pv-volume-claim
  containers:
  - name: redis
    image: redis
    volumeMounts:
      - name: pv-volume-storage
        mountPath: /data/redis
  nodeName: control