apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  namespace: learning
spec:
  capacity:
    storage: 1Gi
  accessModes:
    -   ReadWriteOnce
  hostPath:
    path: "/var/tmp/kubernetes/pv"
 
      

