apiVersion: batch/v1
kind: Job
metadata:
  name: echo-date-better
  namespace: learning
spec:
  parallelism: 2
  completions: 2
  activeDeadlineSeconds: 100
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: echo-date
    spec:
      containers:
        - name: echo
          image: cgr.dev/chainguard/busybox:latest
          command: ["date"]
          resources:
            limits:
              memory: "50Mi"
            requests:
              memory: "50Mi"
              cpu: "250m"
      restartPolicy: OnFailure
          

# Two parallel instances (Pods) can be run for this job and 2 succesful completions are required to be mark job as complete. The jo is allowed to run for 180 seconds if its not completed with 180s it will be marked failed or terminated.
#with backofflimit set to 1, if pod fails it will try to restart it only once.