apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  labels:
    foo: service-label
  annotations:
    bar: service-annotation
spec:
  type: ClusterIP # This is the default value
  selector:
    app: nginx-pods
  ports:
    - protocol: TCP
      port: 80 # Port the service is listening on
      targetPort: 8080 # Port the container is listening on (if unset, defaults to equal port value)
