apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: learning
  labels:
    app: nginx-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pods
  template:
    metadata:
      labels:
        app: nginx-pods
    spec:
      containers:
        - name: nginx
          image: cgr.dev/chainguard/nginx:latest-dev
          securityContext:
            capabilities:
              add: ["NET_RAW"]
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              memory: "50Mi"
            requests:
              memory: "50Mi"
              cpu: "250m"
